### PR TITLE
Testing Packaging v2

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Description

**This require manual testing before we merge it to `master`, feel free to try the update and share the logs! :)**

`sudo yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh/tree/testing --debug`

<details>
<summary>TODO (done)</summary>

- [x] Packaging v2
- [x] Advertise `tootctl media remove` and other media cleanup related commands in `PRE_UPGRADE.md` and `ADMIN.md`
- [x] Advertise `tootctl self-destruct` in `ADMIN.md` ([or PRE_REMOVE.md?](https://github.com/YunoHost/issues/issues/2334))

</details>

Edit: I deleted some `!testme` comments and hidden outdated comments to make the thread more legible

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by Tagadda** [comment]
Contributors and admins! We're waiting for some real life feedback before we release this PR!
Feel free to do a backup, run `sudo yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh/tree/testing --debug` and report your findings here :)

[Forum Announcement](https://forum.yunohost.org/t/mastodon-a-free-open-source-social-network/2768/63?u=tagada)

**Comment by Tagadda** [comment]
Heh, it's broken right now... Assets are 404

**Comment by panomaki** [comment]
On a test VM (Virtualbox), upgrading from a 4.2 install went well (though slow). Will try out on a different machine later this week.

**Comment by Salamandar** [comment]
Same, works fine on ynh-dev.

**Review by Salamandar — APPROVED** [review]

**Comment by OniriCorpe** [comment]
the "Advertise tootctl media remove and other media cleanup related commands in PRE_UPGRADE.md and ADMIN.md" is not done, maybe wait for it before merge?

**Comment by Tagadda** [comment]
Si ça marche chez vous

**Comment by Salamandar** [comment]
@Tagadda after vocal discussion we understood that fresh install works but upgrade doesn't.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
I am very tempted to merge 😬

**Comment by Salamandar** [comment]
> Heh, it's broken right now... Assets are 404 image

Fixed, was due to install_dir being owned by mastodon:mastodon during an upgrade.

**Review by Salamandar — APPROVED** [review]
After some fixes and some install / upgrade tests, LGTM. No 404 anymore, and databases are migrated/renamed properly.

**Pull request merged**
