### PR TITLE
Implement ldap_enabled

### LINKED ISSUE #220: Mastodon Password Reset is broken when LDAP authentication is activated
Mastodon allows users to be invited via URL. User accounts created this way cannot reset their password, they get the message: 

> You are logged in via an external service, so password and e-mail settings are not available.

As an admin, I don't have any further options to assist the user with resetting their password.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Fix #220*

## Solution
- *Implement ldap_enabled*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/mastodon_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by Tagadda** [comment]
I think enable ldap should close registration to prevent #220.

**Comment by yalh76** [comment]
> 
> 
> I think enabling ldap should close registration to prevent #220.

For #220, it's more invitations that we need to disable, but I didn't find how to do that....

**Comment by yalh76** [comment]
to disable registrations: https://github.com/tootsuite/mastodon/blob/master/config/settings.yml

**Comment by yalh76** [comment]
after reflexion, seems to have too much side effect to allow someone to easily switch from an ldap authenticated no a non ldap authenticated mastodon instance

**Pull request closed without merging**
