### PR TITLE
Packaging v2

### PR DESCRIPTION
**Pull request by Tagadda**
## Description

- [x] Packaging v2
- [ ] Advertise `tootctl media remove` and other media cleanup related commands in `PRE_UPGRADE.md` and `ADMIN.md`
- [x] Advertise `tootctl self-destruct` in `ADMIN.md` ([or PRE_REMOVE.md?](https://github.com/YunoHost/issues/issues/2334))

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Tagadda** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
!!

**Pull request merged**
