### PR TITLE
Updated to 2.5.0 and added Nginx : CSP as suggested by @frju365 

### PR DESCRIPTION
**Pull request by anmol26s**
This PR will add Nginx : CSP as suggested by @frju365 and merging after resolving the conflict will have updated version 2.5.0.

Should also rectify double nginx command hinted here https://github.com/YunoHost-Apps/mastodon_ynh/commit/19c46d2d2bf3a02aba89ee0596f8b5f95e15a642#commitcomment-30373672 after the resolving the conflict.

### CODE REVIEW

**Comment by frju365** [comment]
I don't see where it fixes the double-nginx command ?

Just remove  : https://github.com/YunoHost-Apps/mastodon_ynh/blob/develop/scripts/install#L277-L280

**Comment by anmol26s** [comment]
Ok fixed, now.

**Comment by frju365** [comment]
Thanks. (I don't think we must even reload nginx as the helper normally do that).

**Comment by nemsia** [comment]
It's ok for me, I merge it ?

**Comment by frju365** [comment]
mh... yes, I think it's ok.

**Pull request merged**
