### PR TITLE
Call tootctl self-destruct when the app is remove with purge

### LINKED ISSUE #340: Remove script doesn't call the tootctl self-destruct command
### Describe the bug

When you want to delete your instance from the federation, you need to run `tootctl self-destruct`
> Erase this server from the federation by broadcasting account Delete activities to all known other servers. This allows a “clean exit” from running a Mastodon server, as it leaves next to no cache behind on other servers. This command is always interactive and requires confirmation twice.
> 
> No local data is actually deleted, because emptying the database or deleting the entire VPS is faster. If you run this command then continue to operate the instance anyway, then there will be a state mismatch that might lead to glitches and issues with federation.

https://docs.joinmastodon.org/admin/tootctl/#self-destruct

### Expected behavior

TBD

:warning: We don't want to run this command when the package is removed automagically during a failure.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #340*

## Solution

- *Add the selfdestruct when purge is used*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by lapineige** [comment]
Timed out but all went fine until backup and restore. Which means remove works.
Restarting.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Review by Tagadda — APPROVED** [review]

**Comment by lapineige** [comment]
Let's merge ?

**Comment by Tagadda** [comment]
This feature needs documentation somewhere I guess... in the ADMIN.md ?

**Comment by lapineige** [comment]
Yes clearly.

**Comment by Tagadda** [comment]
We can't run self-destruct and remove everything right away.

> A running Sidekiq process is required, so do not shut down the server until the queues are fully cleared.

https://docs.joinmastodon.org/admin/tootctl/#self-destruct

**Pull request closed without merging**
