### PR TITLE
Patch Gemfile to fix blurhash and ox packages

### LINKED ISSUE #357: Cannot install on new instance
### Describe the bug

* Trying to install Mastodon on new Yunohost instance and new server. Gives error and rolls back. 

### Context

Intel 2x with 12 cores and 12 GB ram, 1 TB HD

env:
  YNH_APP_ARG_ADMIN: bishop
  YNH_APP_ARG_DOMAIN: maindomain.tld
  YNH_APP_ARG_IS_PUBLIC: '0'
  YNH_APP_ARG_LANGUAGE: en_EN
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_8ui18eyx
  YNH_APP_ID: mastodon
  YNH_APP_INSTANCE_NAME: mastodon
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 4.0.2~ynh1
  YNH_ARCH: amd64
error: An error occurred inside the app installation script
interface: api
operation: app_install
parent: null
related_to:
- - app
  - mastodon
started_at: 2022-12-28 08:37:28.317419
success: false
yunohost_version: 11.0.10.2

### Steps to reproduce

Going thru web interface and clicking on install Mastodon in the application list. 

### Expected behavior

*It should install. 

### Logs

* https://paste.yunohost.org/raw/emipowuvik

### PR DESCRIPTION
**Pull request by badrihippo**
## Problem

Mastodon wasn't installing (or upgrading) properly because the `blurhash` package was broken with newer versions of Ruby/gem. This has been described in several issues, including in https://github.com/YunoHost-Apps/mastodon_ynh/issues/357

Additionally, using the fixed version of `blurhash` created similar errors with `ox` as described in https://github.com/ohler55/ox/issues/300

Close #357 

## Solution

Fixes have been made to both `blurhash` (https://github.com/Gargron/blurhash/pull/20) and `ox` (https://github.com/ohler55/ox/pull/301). However, these are yet to make it to a new release. To make Mastodon work before that, I've patched `Gemfile` and `Gemfile.lock` to install the two packages directly from their respective git repos. (I've locked them to the specific commits of the fixes, so we won't unintentionally add other updates as well).

If this PR is accepted, we should probably leave a note somewhere to remove the patch when newer versions of `blurhash` and `ox` come out.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested

## Automatic tests

I'm not part of the Yunohost-Apps organisation, so someone with the powers please invoke this :slightly_smiling_face:

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by badrihippo** [comment]
Some of the tests are saying "unable to install mastodon" because mastodon is already installed (or that the domain is already full)!

Is this a CI thing or does something in the code need fixing?  :eyes:

**Comment by yalh76** [comment]
> Some of the tests are saying "unable to install mastodon" because mastodon is already installed (or that the domain is already full)!
> 
> Is this a CI thing or does something in the code need fixing? 👀
> 
> **Edit:** looks like other tests around the same time are affected with the same problem too

Yes more a CI dev issue

**Comment by oufmilo** [comment]
i've launched it on my personnal yunorunner

[Test Badge](https://yunorunner.travelpandas.eu/ci/job/3)
[](https://yunorunner.travelpandas.eu/ci/job/3)

**Comment by badrihippo** [comment]
Yay! Thank you :slightly_smiling_face:

I didn't realise yunorunner was a thing, but now I see it even has a yunohost package. Of _course_ it has a yunohost package :stuck_out_tongue:

Warning: the upgrade works but earlier upgrades break; possibly because of version mismatches after the version patch? Not sure if that's a concern...

**Comment by oufmilo** [comment]
You welcome!

Yes i've seen that. i think it's not a problem and maybe we should remove upgrade from earlier versions

**Comment by yalh76** [comment]
> Yay! Thank you 🙂
> 
> I didn't realise yunorunner was a thing, but now I see it even has a yunohost package. Of _course_ it has a yunohost package 😛
> 
> Warning: the upgrade works but earlier upgrades break; possibly because of version mismatches after the version patch? Not sure if that's a concern...

Nope, upgrade from previous upgrade fails because install of previous version fails

**Comment by badrihippo** [comment]
> Nope, upgrade from previous versions fails because install of previous version fails

Oh of course, I should have thought of that! :facepalm:

**Pull request merged**
