### PR TITLE
Add a check that there's a reasonable quantity of RAM+swap available

### PR DESCRIPTION
**Pull request by alexAubin**
Suggesting to add this check at the beginning of the install script so that people trying to naively install this app get this info directly instead of encountering the whole ruby stacktrace complaining that `virtual memory exhausted: Cannot allocate memory` :wink: 

N.B. : I only tested these few lines using a small bash script (not running the `yunohost install` itself) ...

### CODE REVIEW

**Comment by anmol26s** [comment]
Is there a way to merge this code in two branches develop and master simultaneously ?

**Comment by alexAubin** [comment]
>Is there a way to merge this code in two branches develop and master simultaneously ?

I guess yes, the easiest way would be to merge in develop, then in master ...

But if you have commits awaiting in develop that you don't wish to release yet, then I think you can : 
- merge in master
- cherry-pick the corresponding commit in develop

**Comment by alexAubin** [comment]
Bumpz

idk what to do with this (we can merge in master or testing, anything that's fine with you guys)

**Comment by anmol26s** [comment]
I have changed the branch to master. There are some conflicts which need to be fixed.

**Comment by alexAubin** [comment]
ping @anmol26s  : c.f. https://github.com/YunoHost-Apps/mastodon_ynh/pull/129

**Pull request closed without merging**
