### PR TITLE
ynh_install_ruby__2

### PR DESCRIPTION
**Pull request by yalh76**
## Solution
- *ynh_install_ruby__2*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
# Own CI result for Revision: 0337521cde48b451846f680add7dc0ed18d5545a 

image

**Review by alexAubin — APPROVED** [review]
Naive LGTM but i don't have super huge knowledge of ruby etc

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
#Own CI result for Revision: 00d4516409fae2e6e3afec092e491bc8dba5fff4

image

**Pull request merged**
