### PR TITLE
Testing - Upgrade to v4.2.0 (#409)

### PR DESCRIPTION
**Pull request by Tagadda**
## Description

- #409 
- [Bump ruby version to 3.2.2](https://github.com/YunoHost-Apps/mastodon_ynh/commit/8d5fb2fe51764776d11898f4e7a6f11f00f30888)
- [Disable SSO integration](https://github.com/YunoHost-Apps/mastodon_ynh/commit/d22e37fb861f4fe89eecdc373331814588e01f7d)

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Tagadda** [comment]
@yelvington Wanna try it out before the release ?

**Comment by Tagadda** [comment]
!testme

**Review by panomaki — APPROVED** [review]
Changes look good. Disabling SSO is I think a good step; as issues #349 and #401 show people do want to have the ability to change mastodon instance, which the SSO blocks.

**Comment by Tagadda** [comment]
@panomaki FYI #401 is blocked by LDAP, not SSO
I removed the SSO patch because it was failing to apply on 4.2.0 sources and it will be removed by #399 anyway

**Pull request merged**
