### PR TITLE
[enh] Install tagged release

### PR DESCRIPTION
**Pull request by nemsia**

### CODE REVIEW

**Comment by magikcypress** [comment]
Why not !
But i do not know if it would be better to fix the installation on a release ? As we are sure that the app works on this release and that it is up, the user to make update. If the application crashes, can it go to a good release ?

It could be fixed on version 1.3.1 (last release).
What do you think ?

**Comment by nemsia** [comment]
If you clone the master on a "bad" moment, the installation can be unstable.
On my test of the restore script, It happened to me several times.

**Comment by magikcypress** [comment]
Ok, so it's important to fix the install on a release that works as well ?

**Comment by nemsia** [comment]
It doesn't work ... Sorry.
I close the PR.

**Pull request closed without merging**
